pipeline:
  name: simple_pipeline
  feature: simple  # domain/use-case (Feature > Model > Version > artifacts)
  model_name: simple_model
  version: null  # auto-filled with random ID by mlplatform
  steps:
    - name: train
      type: train
      module: template_model.train
      class: MyTrain

    - name: inference
      type: inference
      module: template_model.predict
      class: MyInference
