name: train
type: train
module: example_model.train
class: MyTrain
envs:
  dev:
    runner: LocalRunner
    storage: LocalFileSystem
    etb: LocalJsonTracker
  local_spark:
    runner: LocalSparkRunner
    storage: LocalFileSystem
    etb: LocalJsonTracker
    runner_config:
      direct: true
      model_package: example_model
  prod:
    runner: DataprocSparkRunner
    storage: LocalFileSystem
    etb: LocalJsonTracker
    runner_config:
      cluster: my-dataproc-cluster
      model_package: example_model
max_iter: 1000
