pipeline_name: example_workflow_sequential
pipeline_type: training
feature_name: example
schedule:
  dev: ""
  qa: "0 0 6 ? * MON"
  prod: "0 0 6 ? * MON"

environments:
  dev: true
  qa: true
  prod: false

tasks:
  - task_id: train_model
    task_type: training
    config:
      - global
      - dev
    model_name: example_model
    compute: s
    training_platform: VertexAI
    module: "example_model.train"
    
  - task_id: evaluation
    task_type: evaluation
    compute: s
    training_platform: VertexAI
    module: "example_model.evaluate"

  - task_id: deploy
    task_type: deploy
    condition_task:
      clause: "{{tasks.evaluation.values.model_updated}}"
      operator: "EQUAL_TO"
      value: "1"
    depends_on:
      - task_id: [evaluation]
